services:
- type: web
  name: enforcedspeed
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --chdir /opt/render/project/src enforcedspeed_wsgi:app --bind
    0.0.0.0:$PORT --access-logfile - --error-logfile -
  healthCheckPath: /healthz
  autoDeploy: true
  envVars:
  - key: FLASK_ENV
    value: production
  - key: SECRET_KEY
    generateValue: true
